### ISSUE TITLE
NO access to Notion

### ISSUE THREAD

**Issue by Saixiaoma** [yeonsikch/Unbiased-Teacher#1]
Thanks for your great work!
I tried to read your notion for some guidance. It shows "You do not have access to yeon의 Notion. Please contact an admin to add you as a member". So how can I get this ?

**Comment by yeonsikch** [comment]
Hi!
Thanks for your mail.

im so sorry that my reply is so late.

I just change that you can read my notion.
but my notion is written in Korean.
https://cypress-father-20f.notion.site/SS-OD-Unbiased-Teacher-c5f85aec178a48bf98a8bcac15e6ff71

And I send you additional new notion pages.
https://cypress-father-20f.notion.site/Semi-Supervised-Object-Detection-for-Small-Imbalanced-Drama-Dataset-8d0b5c2ad20d4962b47b90ff035751e6
https://cypress-father-20f.notion.site/semi-obj-det-unbiased-teacher-c98498d5b6a54049abe09e706018999d

Thank you


2021년 11월 26일 (금) 오전 11:31, Saixiaoma ***@***.***>님이 작성:

**Comment by yeonsikch** [comment]
Hi!
Thanks for your mail.

im so sorry that my reply is so late.

I just change that you can read my notion.
but my notion is written in Korean.
https://cypress-father-20f.notion.site/SS-OD-Unbiased-Teacher-c5f85aec178a48bf98a8bcac15e6ff71

And I send you additional new notion pages.
https://cypress-father-20f.notion.site/Semi-Supervised-Object-Detection-for-Small-Imbalanced-Drama-Dataset-8d0b5c2ad20d4962b47b90ff035751e6
https://cypress-father-20f.notion.site/semi-obj-det-unbiased-teacher-c98498d5b6a54049abe09e706018999d

Thank you

2021년 11월 26일 (금) 오전 11:31, Saixiaoma ***@***.***>님이 작성:

**Comment by Saixiaoma** [comment]
Hi!
Thanks for your reply. This is very useful for my research work.
